version: '3.8'

services:
  cf-analytics:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - PORT=4000
      - NGINX_PORT=80
    
    # 如果使用配置文件方式，取消下面的卷挂载注释
    # volumes:
    #   - ./server/zones.yml:/api/zones.yml:ro
    restart: unless-stopped